services:
  app:
    container_name: app
    build:
      context: ../
      dockerfile: Dockerfile
    env_file: ../.env
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ../:/code-to-cv
    command: ['./entrypoint.sh']
    restart: always
