"""interview_questions

Revision ID: be381c3cc28b
Revises: 624a7a172593
Create Date: 2024-07-22 01:36:43.859654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be381c3cc28b'
down_revision: Union[str, None] = '624a7a172593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_questions',
    sa.Column('question', sa.String(length=512), nullable=False),
    sa.Column('short_answer', sa.String(length=1024), nullable=False),
    sa.Column('full_answer', sa.String(length=2048), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_interview_questions_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_questions')),
    sa.UniqueConstraint('question', name=op.f('uq_interview_questions_question'))
    )
    op.create_index(op.f('ix_interview_questions_slug'), 'interview_questions', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_questions_slug'), table_name='interview_questions')
    op.drop_table('interview_questions')
    # ### end Alembic commands ###
